"""Veritabaninin ilk hali

Revision ID: 49d3f99d8555
Revises: 
Create Date: 2025-09-21 21:58:28.361156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49d3f99d8555'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kasalar_bankalar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hesap_adi', sa.String(), nullable=True),
    sa.Column('kod', sa.String(), nullable=True),
    sa.Column('tip', sa.String(), nullable=True),
    sa.Column('bakiye', sa.Float(), nullable=True),
    sa.Column('para_birimi', sa.String(), nullable=True),
    sa.Column('banka_adi', sa.String(), nullable=True),
    sa.Column('sube_adi', sa.String(), nullable=True),
    sa.Column('hesap_no', sa.String(), nullable=True),
    sa.Column('varsayilan_odeme_turu', sa.String(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('olusturma_tarihi', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kasalar_bankalar', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kasalar_bankalar_hesap_adi'), ['hesap_adi'], unique=False)
        batch_op.create_index(batch_op.f('ix_kasalar_bankalar_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kasalar_bankalar_kod'), ['kod'], unique=True)

    op.create_table('kullanicilar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kullanici_adi', sa.String(), nullable=True),
    sa.Column('sifre_hash', sa.String(), nullable=True),
    sa.Column('ad', sa.String(length=50), nullable=True),
    sa.Column('soyad', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('telefon', sa.String(length=20), nullable=True),
    sa.Column('rol', sa.String(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('olusturma_tarihi', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kullanicilar', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kullanicilar_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_kullanicilar_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kullanicilar_kullanici_adi'), ['kullanici_adi'], unique=True)

    op.create_table('sirketler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sirket_adi', sa.String(), nullable=True),
    sa.Column('sirket_adresi', sa.Text(), nullable=True),
    sa.Column('sirket_telefonu', sa.String(), nullable=True),
    sa.Column('sirket_email', sa.String(), nullable=True),
    sa.Column('sirket_vergi_dairesi', sa.String(), nullable=True),
    sa.Column('sirket_vergi_no', sa.String(), nullable=True),
    sa.Column('sirket_logo_yolu', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sirketler', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sirketler_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sirketler_sirket_adi'), ['sirket_adi'], unique=False)

    op.create_table('cari_hareketler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cari_id', sa.Integer(), nullable=True),
    sa.Column('cari_tip', sa.String(), nullable=False),
    sa.Column('tarih', sa.Date(), nullable=True),
    sa.Column('islem_turu', sa.String(), nullable=True),
    sa.Column('islem_yone', sa.Enum('GIRIS', 'CIKIS', 'BORC', 'ALACAK', name='islemyoneenum'), nullable=True),
    sa.Column('tutar', sa.Float(), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('kaynak', sa.String(), nullable=True),
    sa.Column('kaynak_id', sa.Integer(), nullable=True),
    sa.Column('odeme_turu', sa.Enum('NAKIT', 'KART', 'EFT_HAVALE', 'CEK', 'SENET', 'ACIK_HESAP', 'ETKISIZ_FATURA', name='odemeturuenum'), nullable=True),
    sa.Column('kasa_banka_id', sa.Integer(), nullable=True),
    sa.Column('vade_tarihi', sa.Date(), nullable=True),
    sa.Column('kullanici_id', sa.Integer(), nullable=True),
    sa.Column('olusturma_tarihi_saat', sa.DateTime(), nullable=True),
    sa.Column('olusturan_kullanici_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kasa_banka_id'], ['kasalar_bankalar.id'], ),
    sa.ForeignKeyConstraint(['kullanici_id'], ['kullanicilar.id'], ),
    sa.ForeignKeyConstraint(['olusturan_kullanici_id'], ['kullanicilar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cari_hareketler', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cari_hareketler_cari_id'), ['cari_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cari_hareketler_id'), ['id'], unique=False)

    op.create_table('faturalar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fatura_no', sa.String(), nullable=True),
    sa.Column('fatura_turu', sa.Enum('SATIS', 'ALIS', 'SATIS_IADE', 'ALIS_IADE', 'DEVIR_GIRIS', name='faturaturuenum'), nullable=True),
    sa.Column('tarih', sa.Date(), nullable=True),
    sa.Column('vade_tarihi', sa.Date(), nullable=True),
    sa.Column('cari_id', sa.Integer(), nullable=True),
    sa.Column('misafir_adi', sa.String(), nullable=True),
    sa.Column('odeme_turu', sa.Enum('NAKIT', 'KART', 'EFT_HAVALE', 'CEK', 'SENET', 'ACIK_HESAP', 'ETKISIZ_FATURA', name='odemeturuenum'), nullable=True),
    sa.Column('kasa_banka_id', sa.Integer(), nullable=True),
    sa.Column('fatura_notlari', sa.Text(), nullable=True),
    sa.Column('genel_iskonto_tipi', sa.String(), nullable=True),
    sa.Column('genel_iskonto_degeri', sa.Float(), nullable=True),
    sa.Column('original_fatura_id', sa.Integer(), nullable=True),
    sa.Column('genel_toplam', sa.Float(), nullable=False),
    sa.Column('toplam_kdv_haric', sa.Float(), nullable=False),
    sa.Column('toplam_kdv_dahil', sa.Float(), nullable=False),
    sa.Column('olusturma_tarihi_saat', sa.DateTime(), nullable=True),
    sa.Column('olusturan_kullanici_id', sa.Integer(), nullable=True),
    sa.Column('son_guncelleme_tarihi_saat', sa.DateTime(), nullable=True),
    sa.Column('son_guncelleyen_kullanici_id', sa.Integer(), nullable=True),
    sa.Column('kullanici_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kasa_banka_id'], ['kasalar_bankalar.id'], ),
    sa.ForeignKeyConstraint(['kullanici_id'], ['kullanicilar.id'], ),
    sa.ForeignKeyConstraint(['olusturan_kullanici_id'], ['kullanicilar.id'], ),
    sa.ForeignKeyConstraint(['original_fatura_id'], ['faturalar.id'], ),
    sa.ForeignKeyConstraint(['son_guncelleyen_kullanici_id'], ['kullanicilar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('faturalar', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_faturalar_cari_id'), ['cari_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_faturalar_fatura_no'), ['fatura_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_faturalar_fatura_turu'), ['fatura_turu'], unique=False)
        batch_op.create_index(batch_op.f('ix_faturalar_id'), ['id'], unique=False)

    op.create_table('gelir_siniflandirmalari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(), nullable=True),
    sa.Column('kullanici_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kullanici_id'], ['kullanicilar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gelir_siniflandirmalari', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gelir_siniflandirmalari_ad'), ['ad'], unique=True)
        batch_op.create_index(batch_op.f('ix_gelir_siniflandirmalari_id'), ['id'], unique=False)

    op.create_table('gider_siniflandirmalari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(), nullable=True),
    sa.Column('kullanici_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kullanici_id'], ['kullanicilar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gider_siniflandirmalari', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gider_siniflandirmalari_ad'), ['ad'], unique=True)
        batch_op.create_index(batch_op.f('ix_gider_siniflandirmalari_id'), ['id'], unique=False)

    op.create_table('kasa_banka_hareketleri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kasa_banka_id', sa.Integer(), nullable=True),
    sa.Column('tarih', sa.Date(), nullable=True),
    sa.Column('islem_turu', sa.String(), nullable=True),
    sa.Column('islem_yone', sa.Enum('GIRIS', 'CIKIS', 'BORC', 'ALACAK', name='islemyoneenum'), nullable=True),
    sa.Column('tutar', sa.Float(), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('kaynak', sa.String(), nullable=True),
    sa.Column('kaynak_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kasa_banka_id'], ['kasalar_bankalar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kasa_banka_hareketleri', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kasa_banka_hareketleri_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kasa_banka_hareketleri_kasa_banka_id'), ['kasa_banka_id'], unique=False)

    op.create_table('musteriler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(), nullable=True),
    sa.Column('kod', sa.String(), nullable=True),
    sa.Column('telefon', sa.String(), nullable=True),
    sa.Column('adres', sa.Text(), nullable=True),
    sa.Column('vergi_dairesi', sa.String(), nullable=True),
    sa.Column('vergi_no', sa.String(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('olusturma_tarihi', sa.DateTime(), nullable=True),
    sa.Column('kullanici_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kullanici_id'], ['kullanicilar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('musteriler', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_musteriler_ad'), ['ad'], unique=False)
        batch_op.create_index(batch_op.f('ix_musteriler_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_musteriler_kod'), ['kod'], unique=True)

    op.create_table('tedarikciler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(), nullable=True),
    sa.Column('kod', sa.String(), nullable=True),
    sa.Column('telefon', sa.String(), nullable=True),
    sa.Column('adres', sa.Text(), nullable=True),
    sa.Column('vergi_dairesi', sa.String(), nullable=True),
    sa.Column('vergi_no', sa.String(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('olusturma_tarihi', sa.DateTime(), nullable=True),
    sa.Column('kullanici_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kullanici_id'], ['kullanicilar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tedarikciler', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tedarikciler_ad'), ['ad'], unique=False)
        batch_op.create_index(batch_op.f('ix_tedarikciler_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tedarikciler_kod'), ['kod'], unique=True)

    op.create_table('ulkeler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(), nullable=True),
    sa.Column('kullanici_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kullanici_id'], ['kullanicilar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ulkeler', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ulkeler_ad'), ['ad'], unique=True)
        batch_op.create_index(batch_op.f('ix_ulkeler_id'), ['id'], unique=False)

    op.create_table('urun_birimleri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(), nullable=True),
    sa.Column('kullanici_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kullanici_id'], ['kullanicilar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('urun_birimleri', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_urun_birimleri_ad'), ['ad'], unique=True)
        batch_op.create_index(batch_op.f('ix_urun_birimleri_id'), ['id'], unique=False)

    op.create_table('urun_gruplari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(), nullable=True),
    sa.Column('kullanici_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kullanici_id'], ['kullanicilar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('urun_gruplari', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_urun_gruplari_ad'), ['ad'], unique=True)
        batch_op.create_index(batch_op.f('ix_urun_gruplari_id'), ['id'], unique=False)

    op.create_table('urun_kategorileri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(), nullable=True),
    sa.Column('kullanici_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kullanici_id'], ['kullanicilar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('urun_kategorileri', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_urun_kategorileri_ad'), ['ad'], unique=True)
        batch_op.create_index(batch_op.f('ix_urun_kategorileri_id'), ['id'], unique=False)

    op.create_table('urun_markalari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(), nullable=True),
    sa.Column('kullanici_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kullanici_id'], ['kullanicilar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('urun_markalari', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_urun_markalari_ad'), ['ad'], unique=True)
        batch_op.create_index(batch_op.f('ix_urun_markalari_id'), ['id'], unique=False)

    op.create_table('gelir_giderler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tarih', sa.Date(), nullable=True),
    sa.Column('tip', sa.Enum('GELIR', 'GIDER', name='gelirgidertipenum'), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('tutar', sa.Float(), nullable=True),
    sa.Column('odeme_turu', sa.Enum('NAKIT', 'KART', 'EFT_HAVALE', 'CEK', 'SENET', 'ACIK_HESAP', 'ETKISIZ_FATURA', name='odemeturuenum'), nullable=True),
    sa.Column('kasa_banka_id', sa.Integer(), nullable=True),
    sa.Column('cari_id', sa.Integer(), nullable=True),
    sa.Column('cari_tip', sa.Enum('MUSTERI', 'TEDARIKCI', name='caritipienum'), nullable=True),
    sa.Column('gelir_siniflandirma_id', sa.Integer(), nullable=True),
    sa.Column('gider_siniflandirma_id', sa.Integer(), nullable=True),
    sa.Column('olusturma_tarihi_saat', sa.DateTime(), nullable=True),
    sa.Column('olusturan_kullanici_id', sa.Integer(), nullable=True),
    sa.Column('kullanici_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gelir_siniflandirma_id'], ['gelir_siniflandirmalari.id'], ),
    sa.ForeignKeyConstraint(['gider_siniflandirma_id'], ['gider_siniflandirmalari.id'], ),
    sa.ForeignKeyConstraint(['kasa_banka_id'], ['kasalar_bankalar.id'], ),
    sa.ForeignKeyConstraint(['kullanici_id'], ['kullanicilar.id'], ),
    sa.ForeignKeyConstraint(['olusturan_kullanici_id'], ['kullanicilar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gelir_giderler', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gelir_giderler_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gelir_giderler_tip'), ['tip'], unique=False)

    op.create_table('siparisler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('siparis_no', sa.String(), nullable=True),
    sa.Column('siparis_turu', sa.Enum('SATIS_SIPARIS', 'ALIS_SIPARIS', name='siparisturuenum'), nullable=True),
    sa.Column('durum', sa.Enum('BEKLEMEDE', 'TAMAMLANDI', 'KISMİ_TESLIMAT', 'IPTAL_EDILDI', 'FATURALASTIRILDI', name='siparisdurumenum'), nullable=True),
    sa.Column('tarih', sa.Date(), nullable=True),
    sa.Column('teslimat_tarihi', sa.Date(), nullable=True),
    sa.Column('cari_id', sa.Integer(), nullable=True),
    sa.Column('cari_tip', sa.Enum('MUSTERI', 'TEDARIKCI', name='caritipienum'), nullable=True),
    sa.Column('siparis_notlari', sa.Text(), nullable=True),
    sa.Column('genel_iskonto_tipi', sa.String(), nullable=True),
    sa.Column('genel_iskonto_degeri', sa.Float(), nullable=True),
    sa.Column('fatura_id', sa.Integer(), nullable=True),
    sa.Column('olusturma_tarihi_saat', sa.DateTime(), nullable=True),
    sa.Column('olusturan_kullanici_id', sa.Integer(), nullable=True),
    sa.Column('son_guncelleme_tarihi_saat', sa.DateTime(), nullable=True),
    sa.Column('son_guncelleyen_kullanici_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fatura_id'], ['faturalar.id'], ),
    sa.ForeignKeyConstraint(['olusturan_kullanici_id'], ['kullanicilar.id'], ),
    sa.ForeignKeyConstraint(['son_guncelleyen_kullanici_id'], ['kullanicilar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('siparisler', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_siparisler_cari_id'), ['cari_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_siparisler_cari_tip'), ['cari_tip'], unique=False)
        batch_op.create_index(batch_op.f('ix_siparisler_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_siparisler_siparis_no'), ['siparis_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_siparisler_siparis_turu'), ['siparis_turu'], unique=False)

    op.create_table('stoklar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kod', sa.String(), nullable=True),
    sa.Column('ad', sa.String(), nullable=True),
    sa.Column('detay', sa.Text(), nullable=True),
    sa.Column('miktar', sa.Float(), nullable=True),
    sa.Column('alis_fiyati', sa.Float(), nullable=True),
    sa.Column('satis_fiyati', sa.Float(), nullable=True),
    sa.Column('kdv_orani', sa.Float(), nullable=True),
    sa.Column('min_stok_seviyesi', sa.Float(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('urun_resmi_yolu', sa.String(), nullable=True),
    sa.Column('olusturma_tarihi', sa.DateTime(), nullable=True),
    sa.Column('kategori_id', sa.Integer(), nullable=True),
    sa.Column('marka_id', sa.Integer(), nullable=True),
    sa.Column('urun_grubu_id', sa.Integer(), nullable=True),
    sa.Column('birim_id', sa.Integer(), nullable=True),
    sa.Column('mense_id', sa.Integer(), nullable=True),
    sa.Column('kullanici_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['birim_id'], ['urun_birimleri.id'], ),
    sa.ForeignKeyConstraint(['kategori_id'], ['urun_kategorileri.id'], ),
    sa.ForeignKeyConstraint(['kullanici_id'], ['kullanicilar.id'], ),
    sa.ForeignKeyConstraint(['marka_id'], ['urun_markalari.id'], ),
    sa.ForeignKeyConstraint(['mense_id'], ['ulkeler.id'], ),
    sa.ForeignKeyConstraint(['urun_grubu_id'], ['urun_gruplari.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stoklar', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stoklar_ad'), ['ad'], unique=False)
        batch_op.create_index(batch_op.f('ix_stoklar_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stoklar_kod'), ['kod'], unique=True)

    op.create_table('fatura_kalemleri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fatura_id', sa.Integer(), nullable=True),
    sa.Column('urun_id', sa.Integer(), nullable=True),
    sa.Column('miktar', sa.Float(), nullable=True),
    sa.Column('birim_fiyat', sa.Float(), nullable=True),
    sa.Column('kdv_orani', sa.Float(), nullable=True),
    sa.Column('alis_fiyati_fatura_aninda', sa.Float(), nullable=True),
    sa.Column('iskonto_yuzde_1', sa.Float(), nullable=True),
    sa.Column('iskonto_yuzde_2', sa.Float(), nullable=True),
    sa.Column('iskonto_tipi', sa.String(), nullable=True),
    sa.Column('iskonto_degeri', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['fatura_id'], ['faturalar.id'], ),
    sa.ForeignKeyConstraint(['urun_id'], ['stoklar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fatura_kalemleri', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fatura_kalemleri_fatura_id'), ['fatura_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fatura_kalemleri_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fatura_kalemleri_urun_id'), ['urun_id'], unique=False)

    op.create_table('siparis_kalemleri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('siparis_id', sa.Integer(), nullable=True),
    sa.Column('urun_id', sa.Integer(), nullable=True),
    sa.Column('miktar', sa.Float(), nullable=True),
    sa.Column('birim_fiyat', sa.Float(), nullable=True),
    sa.Column('kdv_orani', sa.Float(), nullable=True),
    sa.Column('iskonto_yuzde_1', sa.Float(), nullable=True),
    sa.Column('iskonto_yuzde_2', sa.Float(), nullable=True),
    sa.Column('iskonto_tipi', sa.String(), nullable=True),
    sa.Column('iskonto_degeri', sa.Float(), nullable=True),
    sa.Column('alis_fiyati_siparis_aninda', sa.Float(), nullable=True),
    sa.Column('satis_fiyati_siparis_aninda', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['siparis_id'], ['siparisler.id'], ),
    sa.ForeignKeyConstraint(['urun_id'], ['stoklar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('siparis_kalemleri', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_siparis_kalemleri_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_siparis_kalemleri_siparis_id'), ['siparis_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_siparis_kalemleri_urun_id'), ['urun_id'], unique=False)

    op.create_table('stok_hareketleri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stok_id', sa.Integer(), nullable=True),
    sa.Column('tarih', sa.Date(), nullable=True),
    sa.Column('islem_tipi', sa.Enum('GİRİŞ', 'ÇIKIŞ', 'SAYIM_FAZLASI', 'SAYIM_EKSİĞİ', 'SATIŞ', 'ALIŞ', 'SATIŞ_İADE', 'ALIŞ_İADE', 'KONSİNYE_GİRİŞ', 'KONSİNYE_ÇIKIŞ', name='stokislemtipienum'), nullable=True),
    sa.Column('miktar', sa.Float(), nullable=True),
    sa.Column('birim_fiyat', sa.Float(), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('kaynak', sa.String(), nullable=True),
    sa.Column('kaynak_id', sa.Integer(), nullable=True),
    sa.Column('onceki_stok', sa.Float(), nullable=True),
    sa.Column('sonraki_stok', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['stok_id'], ['stoklar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stok_hareketleri', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stok_hareketleri_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stok_hareketleri_stok_id'), ['stok_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stok_hareketleri', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stok_hareketleri_stok_id'))
        batch_op.drop_index(batch_op.f('ix_stok_hareketleri_id'))

    op.drop_table('stok_hareketleri')
    with op.batch_alter_table('siparis_kalemleri', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_siparis_kalemleri_urun_id'))
        batch_op.drop_index(batch_op.f('ix_siparis_kalemleri_siparis_id'))
        batch_op.drop_index(batch_op.f('ix_siparis_kalemleri_id'))

    op.drop_table('siparis_kalemleri')
    with op.batch_alter_table('fatura_kalemleri', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fatura_kalemleri_urun_id'))
        batch_op.drop_index(batch_op.f('ix_fatura_kalemleri_id'))
        batch_op.drop_index(batch_op.f('ix_fatura_kalemleri_fatura_id'))

    op.drop_table('fatura_kalemleri')
    with op.batch_alter_table('stoklar', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stoklar_kod'))
        batch_op.drop_index(batch_op.f('ix_stoklar_id'))
        batch_op.drop_index(batch_op.f('ix_stoklar_ad'))

    op.drop_table('stoklar')
    with op.batch_alter_table('siparisler', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_siparisler_siparis_turu'))
        batch_op.drop_index(batch_op.f('ix_siparisler_siparis_no'))
        batch_op.drop_index(batch_op.f('ix_siparisler_id'))
        batch_op.drop_index(batch_op.f('ix_siparisler_cari_tip'))
        batch_op.drop_index(batch_op.f('ix_siparisler_cari_id'))

    op.drop_table('siparisler')
    with op.batch_alter_table('gelir_giderler', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gelir_giderler_tip'))
        batch_op.drop_index(batch_op.f('ix_gelir_giderler_id'))

    op.drop_table('gelir_giderler')
    with op.batch_alter_table('urun_markalari', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_urun_markalari_id'))
        batch_op.drop_index(batch_op.f('ix_urun_markalari_ad'))

    op.drop_table('urun_markalari')
    with op.batch_alter_table('urun_kategorileri', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_urun_kategorileri_id'))
        batch_op.drop_index(batch_op.f('ix_urun_kategorileri_ad'))

    op.drop_table('urun_kategorileri')
    with op.batch_alter_table('urun_gruplari', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_urun_gruplari_id'))
        batch_op.drop_index(batch_op.f('ix_urun_gruplari_ad'))

    op.drop_table('urun_gruplari')
    with op.batch_alter_table('urun_birimleri', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_urun_birimleri_id'))
        batch_op.drop_index(batch_op.f('ix_urun_birimleri_ad'))

    op.drop_table('urun_birimleri')
    with op.batch_alter_table('ulkeler', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ulkeler_id'))
        batch_op.drop_index(batch_op.f('ix_ulkeler_ad'))

    op.drop_table('ulkeler')
    with op.batch_alter_table('tedarikciler', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tedarikciler_kod'))
        batch_op.drop_index(batch_op.f('ix_tedarikciler_id'))
        batch_op.drop_index(batch_op.f('ix_tedarikciler_ad'))

    op.drop_table('tedarikciler')
    with op.batch_alter_table('musteriler', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_musteriler_kod'))
        batch_op.drop_index(batch_op.f('ix_musteriler_id'))
        batch_op.drop_index(batch_op.f('ix_musteriler_ad'))

    op.drop_table('musteriler')
    with op.batch_alter_table('kasa_banka_hareketleri', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kasa_banka_hareketleri_kasa_banka_id'))
        batch_op.drop_index(batch_op.f('ix_kasa_banka_hareketleri_id'))

    op.drop_table('kasa_banka_hareketleri')
    with op.batch_alter_table('gider_siniflandirmalari', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gider_siniflandirmalari_id'))
        batch_op.drop_index(batch_op.f('ix_gider_siniflandirmalari_ad'))

    op.drop_table('gider_siniflandirmalari')
    with op.batch_alter_table('gelir_siniflandirmalari', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gelir_siniflandirmalari_id'))
        batch_op.drop_index(batch_op.f('ix_gelir_siniflandirmalari_ad'))

    op.drop_table('gelir_siniflandirmalari')
    with op.batch_alter_table('faturalar', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_faturalar_id'))
        batch_op.drop_index(batch_op.f('ix_faturalar_fatura_turu'))
        batch_op.drop_index(batch_op.f('ix_faturalar_fatura_no'))
        batch_op.drop_index(batch_op.f('ix_faturalar_cari_id'))

    op.drop_table('faturalar')
    with op.batch_alter_table('cari_hareketler', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cari_hareketler_id'))
        batch_op.drop_index(batch_op.f('ix_cari_hareketler_cari_id'))

    op.drop_table('cari_hareketler')
    with op.batch_alter_table('sirketler', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sirketler_sirket_adi'))
        batch_op.drop_index(batch_op.f('ix_sirketler_id'))

    op.drop_table('sirketler')
    with op.batch_alter_table('kullanicilar', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kullanicilar_kullanici_adi'))
        batch_op.drop_index(batch_op.f('ix_kullanicilar_id'))
        batch_op.drop_index(batch_op.f('ix_kullanicilar_email'))

    op.drop_table('kullanicilar')
    with op.batch_alter_table('kasalar_bankalar', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kasalar_bankalar_kod'))
        batch_op.drop_index(batch_op.f('ix_kasalar_bankalar_id'))
        batch_op.drop_index(batch_op.f('ix_kasalar_bankalar_hesap_adi'))

    op.drop_table('kasalar_bankalar')
    # ### end Alembic commands ###
